# Generated by Django 3.1.2 on 2020-10-30 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blorejobs',
            new_name='mumbaijobs',
        ),
    ]
